### ISSUE TITLE
App received 400 error when running sample

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure-Samples/active-directory-python-webapp-graphapi#13]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow instructions in README.  (Create app registration, insert data into config.py, call localhost:5000 in browser)

### Any log messages given by the failure
```
werkzeug.exceptions.BadRequestKeyError
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

Traceback (most recent call last)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/thfalgou/git/Azure-Samples/active-directory-python-webapp-graphapi/app.py", line 44, in main_logic
code = flask.request.args['code']
File "/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

### Expected/desired behavior
>  Expected not to receive 400 error

### OS and Version?
> OSX 

### Versions
> OSX 10.12

### Mention any other details that might be useful
I'm using the microsoft.onmicrosoft.com tenant (as an blue-badge employee)

**Comment by lastcoolnameleft** [comment]
NOTE:  The first time I went to localhost:5000, I accepted the auth request, accepted it, and then received this error.  Minutes later, I loaded localhost:5000, got the same auth request, and then accepted it and then did NOT get the error.

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Python library. Check it out: https://github.com/Azure-Samples/ms-identity-python-webapp
You may ask further questions on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
